/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smartkantin.view;

import com.smartkantin.controller.dashboard.PendapatanController;
import com.smartkantin.dto.dashboard.pendapatan.PendapatanKantin;
import com.smartkantin.dto.menu.DaftarSiswaModel;
import com.smartkantin.dto.menu.KonfirmasiDialog;
import com.smartkantin.dto.menu.TableTransfer;
import com.smartkantin.dto.menu.TableTransferModel;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;

public class Dashboard extends javax.swing.JFrame {

    private PendapatanController control = new PendapatanController();
    private PendapatanKantin kantin = control.getListKantin();
    
    public Dashboard() {
        initComponents();
//        remove all panel
        pnlContent.removeAll();
        pnlContent.repaint();
        pnlContent.revalidate();
        
//        add new panel
        pnlContent.add(pnlDashboard);
        pnlContent.repaint();
        pnlContent.revalidate(); 

    }
    public Dashboard(String title) {
        super(title);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnDaftarSiswa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnTableTransfer = new javax.swing.JButton();
        btnIsiSaldo = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnPengguna = new javax.swing.JButton();
        btnTentang = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        pnlDashboard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cardKantin2 = new javax.swing.JButton();
        cardKantin3 = new javax.swing.JButton();
        cardKantin1 = new javax.swing.JButton();
        pnlDaftarSiswa = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDaftarSiswa = new javax.swing.JTable();
        pnlTableTransfer = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        scrlTableTransfer = new javax.swing.JScrollPane();
        tblTransfer = new javax.swing.JTable();
        pnlIsiSaldo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        pnlLaporan = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        pnlPengguna = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnSimpanProfile = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfProfileUsername = new javax.swing.JTextField();
        tfProfilePassword = new javax.swing.JPasswordField();
        btnShowProfilePassword = new javax.swing.JButton();
        pnlTableTransferBackup = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        scrlTableTransfer1 = new javax.swing.JScrollPane();
        tblTransfer1 = new javax.swing.JTable();
        btnKonfirm1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));

        mainPanel.setMinimumSize(new java.awt.Dimension(1366, 768));
        mainPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        mainPanel.setLayout(null);

        menuPanel.setBackground(new java.awt.Color(102, 204, 255));
        menuPanel.setMinimumSize(new java.awt.Dimension(360, 768));
        menuPanel.setPreferredSize(new java.awt.Dimension(350, 1000));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Smart Kantin");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText(" Desktop Version");

        btnDashboard.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(null);
        btnDashboard.setBorderPainted(false);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard.setIconTextGap(12);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnDaftarSiswa.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnDaftarSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/daftar-siswa.png"))); // NOI18N
        btnDaftarSiswa.setText("Daftar Siswa");
        btnDaftarSiswa.setBorder(null);
        btnDaftarSiswa.setBorderPainted(false);
        btnDaftarSiswa.setContentAreaFilled(false);
        btnDaftarSiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDaftarSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDaftarSiswa.setIconTextGap(20);
        btnDaftarSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarSiswaActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/smartkantin-beranda.png"))); // NOI18N

        btnTableTransfer.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnTableTransfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/daftar-penjual1.png"))); // NOI18N
        btnTableTransfer.setText("Table Transfer");
        btnTableTransfer.setBorder(null);
        btnTableTransfer.setBorderPainted(false);
        btnTableTransfer.setContentAreaFilled(false);
        btnTableTransfer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTableTransfer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTableTransfer.setIconTextGap(15);
        btnTableTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableTransferActionPerformed(evt);
            }
        });

        btnIsiSaldo.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnIsiSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/isi-saldo.png"))); // NOI18N
        btnIsiSaldo.setText("Isi Saldo");
        btnIsiSaldo.setBorder(null);
        btnIsiSaldo.setBorderPainted(false);
        btnIsiSaldo.setContentAreaFilled(false);
        btnIsiSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIsiSaldo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnIsiSaldo.setIconTextGap(-2);
        btnIsiSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsiSaldoActionPerformed(evt);
            }
        });

        btnLaporan.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/laporan.png"))); // NOI18N
        btnLaporan.setText("Laporan");
        btnLaporan.setBorder(null);
        btnLaporan.setBorderPainted(false);
        btnLaporan.setContentAreaFilled(false);
        btnLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaporan.setIconTextGap(10);
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        btnPengguna.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pengguna.png"))); // NOI18N
        btnPengguna.setText("Pengguna");
        btnPengguna.setBorder(null);
        btnPengguna.setBorderPainted(false);
        btnPengguna.setContentAreaFilled(false);
        btnPengguna.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPengguna.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPengguna.setIconTextGap(10);
        btnPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenggunaActionPerformed(evt);
            }
        });

        btnTentang.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnTentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tentang.png"))); // NOI18N
        btnTentang.setText("Tentang");
        btnTentang.setBorder(null);
        btnTentang.setBorderPainted(false);
        btnTentang.setContentAreaFilled(false);
        btnTentang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTentang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTentang.setIconTextGap(13);
        btnTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentangActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/keluar.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setBorder(null);
        btnKeluar.setBorderPainted(false);
        btnKeluar.setContentAreaFilled(false);
        btnKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKeluar.setIconTextGap(10);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTentang, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIsiSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(menuPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnTableTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuPanelLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDaftarSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 50, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addComponent(btnDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDaftarSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTableTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIsiSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPengguna)
                .addGap(10, 10, 10)
                .addComponent(btnTentang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeluar)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        mainPanel.add(menuPanel);
        menuPanel.setBounds(0, 0, 360, 50000);

        pnlContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlContent.setPreferredSize(new java.awt.Dimension(1125, 845));

        pnlDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 64)); // NOI18N
        jLabel5.setText("Dashboard");

        cardKantin2.setBackground(new java.awt.Color(153, 153, 255));
        cardKantin2.setFont(new java.awt.Font("DejaVu Sans", 0, 48)); // NOI18N
        cardKantin2.setForeground(new java.awt.Color(255, 255, 255));
        cardKantin2.setText("Kantin 2");
        cardKantin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardKantin2ActionPerformed(evt);
            }
        });

        cardKantin3.setBackground(new java.awt.Color(153, 153, 255));
        cardKantin3.setFont(new java.awt.Font("DejaVu Sans", 0, 48)); // NOI18N
        cardKantin3.setForeground(new java.awt.Color(255, 255, 255));
        cardKantin3.setText("Kantin 3");
        cardKantin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardKantin3ActionPerformed(evt);
            }
        });

        cardKantin1.setBackground(new java.awt.Color(153, 153, 255));
        cardKantin1.setFont(new java.awt.Font("DejaVu Sans", 0, 48)); // NOI18N
        cardKantin1.setForeground(new java.awt.Color(255, 255, 255));
        cardKantin1.setText("Kantin 1");
        cardKantin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardKantin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel5))
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlDashboardLayout.createSequentialGroup()
                                .addComponent(cardKantin3, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(540, 540, 540))
                            .addGroup(pnlDashboardLayout.createSequentialGroup()
                                .addComponent(cardKantin1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(cardKantin2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(61, 61, 61)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardKantin1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardKantin2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(cardKantin3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDaftarSiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDaftarSiswa.setPreferredSize(new java.awt.Dimension(1125, 845));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 64)); // NOI18N
        jLabel7.setText("Daftar Siswa");

        jPanel4.setLayout(new java.awt.CardLayout());

        tblDaftarSiswa.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        tblDaftarSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDaftarSiswa.setRowHeight(50);
        tblDaftarSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDaftarSiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDaftarSiswa);

        jPanel4.add(jScrollPane2, "card2");

        javax.swing.GroupLayout pnlDaftarSiswaLayout = new javax.swing.GroupLayout(pnlDaftarSiswa);
        pnlDaftarSiswa.setLayout(pnlDaftarSiswaLayout);
        pnlDaftarSiswaLayout.setHorizontalGroup(
            pnlDaftarSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlDaftarSiswaLayout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(jLabel7))
        );
        pnlDaftarSiswaLayout.setVerticalGroup(
            pnlDaftarSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaftarSiswaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlTableTransfer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlTableTransfer.setPreferredSize(new java.awt.Dimension(1125, 845));
        pnlTableTransfer.setLayout(null);

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 64)); // NOI18N
        jLabel9.setText("Table Transfer");
        pnlTableTransfer.add(jLabel9);
        jLabel9.setBounds(430, 30, 462, 76);

        tblTransfer.setAutoCreateRowSorter(true);
        tblTransfer.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        tblTransfer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransfer.setRowHeight(50);
        tblTransfer.setRowMargin(1

        );
        tblTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransferMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblTransferMouseEntered(evt);
            }
        });
        scrlTableTransfer.setViewportView(tblTransfer);

        pnlTableTransfer.add(scrlTableTransfer);
        scrlTableTransfer.setBounds(0, 120, 1370, 820);

        pnlIsiSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlIsiSaldo.setPreferredSize(new java.awt.Dimension(1125, 845));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 64)); // NOI18N
        jLabel6.setText("Isi Saldo");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel3.setText("Id Siswa");

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel8.setText("Nominal");

        jTextField1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jButton5.setText("Kirim");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlIsiSaldoLayout = new javax.swing.GroupLayout(pnlIsiSaldo);
        pnlIsiSaldo.setLayout(pnlIsiSaldoLayout);
        pnlIsiSaldoLayout.setHorizontalGroup(
            pnlIsiSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIsiSaldoLayout.createSequentialGroup()
                .addGroup(pnlIsiSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlIsiSaldoLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel6))
                    .addGroup(pnlIsiSaldoLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel3)
                        .addGap(121, 121, 121)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlIsiSaldoLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel8)
                        .addGap(122, 122, 122)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIsiSaldoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addGap(265, 265, 265))
        );
        pnlIsiSaldoLayout.setVerticalGroup(
            pnlIsiSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIsiSaldoLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel6)
                .addGap(84, 84, 84)
                .addGroup(pnlIsiSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(pnlIsiSaldoLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(pnlIsiSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIsiSaldoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton5)
                .addContainerGap())
        );

        pnlLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlLaporan.setPreferredSize(new java.awt.Dimension(1125, 845));
        pnlLaporan.setLayout(null);

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 64)); // NOI18N
        jLabel13.setText("Laporan Kantin");
        pnlLaporan.add(jLabel13);
        jLabel13.setBounds(321, 30, 487, 76);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlLaporan.add(jPanel6);
        jPanel6.setBounds(0, 118, 1297, 826);

        pnlPengguna.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlPengguna.setPreferredSize(new java.awt.Dimension(1125, 845));
        pnlPengguna.setLayout(null);

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 64)); // NOI18N
        jLabel10.setText("Pengguna");
        pnlPengguna.add(jLabel10);
        jLabel10.setBounds(68, 106, 360, 76);

        btnSimpanProfile.setBackground(new java.awt.Color(153, 153, 255));
        btnSimpanProfile.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        btnSimpanProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanProfile.setText("Simpan");
        btnSimpanProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanProfileActionPerformed(evt);
            }
        });
        pnlPengguna.add(btnSimpanProfile);
        btnSimpanProfile.setBounds(780, 570, 190, 60);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile-pengguna.png"))); // NOI18N
        pnlPengguna.add(jLabel11);
        jLabel11.setBounds(140, 300, 300, 310);

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel12.setText("Password");
        pnlPengguna.add(jLabel12);
        jLabel12.setBounds(460, 470, 150, 70);

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel14.setText("Username");
        pnlPengguna.add(jLabel14);
        jLabel14.setBounds(460, 380, 150, 70);

        tfProfileUsername.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        tfProfileUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProfileUsernameActionPerformed(evt);
            }
        });
        pnlPengguna.add(tfProfileUsername);
        tfProfileUsername.setBounds(613, 381, 358, 70);

        tfProfilePassword.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        tfProfilePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProfilePasswordActionPerformed(evt);
            }
        });
        pnlPengguna.add(tfProfilePassword);
        tfProfilePassword.setBounds(613, 469, 300, 70);

        btnShowProfilePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/closed-eye.png"))); // NOI18N
        btnShowProfilePassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnShowProfilePassword.setBorderPainted(false);
        btnShowProfilePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowProfilePasswordMouseClicked(evt);
            }
        });
        btnShowProfilePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowProfilePasswordActionPerformed(evt);
            }
        });
        pnlPengguna.add(btnShowProfilePassword);
        btnShowProfilePassword.setBounds(910, 470, 60, 70);

        pnlTableTransferBackup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlTableTransferBackup.setEnabled(false);
        pnlTableTransferBackup.setPreferredSize(new java.awt.Dimension(1125, 845));
        pnlTableTransferBackup.setLayout(null);

        jLabel15.setFont(new java.awt.Font("sansserif", 0, 64)); // NOI18N
        jLabel15.setText("Table Transfer");
        pnlTableTransferBackup.add(jLabel15);
        jLabel15.setBounds(68, 106, 462, 76);

        tblTransfer1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        tblTransfer1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransfer1.setRowHeight(50);
        tblTransfer1.setRowMargin(1

        );
        tblTransfer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransfer1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblTransfer1MouseEntered(evt);
            }
        });
        scrlTableTransfer1.setViewportView(tblTransfer1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(scrlTableTransfer1, javax.swing.GroupLayout.PREFERRED_SIZE, 1392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlTableTransfer1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlTableTransferBackup.add(jPanel7);
        jPanel7.setBounds(6, 215, 1392, 630);

        btnKonfirm1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnKonfirm1.setText("Konfirmasi");
        btnKonfirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirm1ActionPerformed(evt);
            }
        });
        pnlTableTransferBackup.add(btnKonfirm1);
        btnKonfirm1.setBounds(1220, 150, 180, 43);

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1420, Short.MAX_VALUE)
            .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlContentLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlTableTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, 1408, Short.MAX_VALUE)
                        .addComponent(pnlLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 1408, Short.MAX_VALUE)
                        .addComponent(pnlDaftarSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 1408, Short.MAX_VALUE)
                        .addComponent(pnlIsiSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 1408, Short.MAX_VALUE))
                    .addGap(6, 6, 6)))
            .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlPengguna, javax.swing.GroupLayout.DEFAULT_SIZE, 1408, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlContentLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(pnlTableTransferBackup, javax.swing.GroupLayout.DEFAULT_SIZE, 1408, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlContentLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlTableTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                        .addComponent(pnlLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                        .addComponent(pnlDaftarSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                        .addComponent(pnlIsiSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                        .addComponent(pnlDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(6, 6, 6)))
            .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlPengguna, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlContentLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(pnlTableTransferBackup, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
        );

        mainPanel.add(pnlContent);
        pnlContent.setBounds(360, 0, 1420, 960);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1783, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        showMenuBtn(pnlDashboard, btnDashboard);
        
        btnDashboard.setForeground(Color.WHITE);
        btnDaftarSiswa.setForeground(Color.BLACK);
        btnTableTransfer.setForeground(Color.BLACK);
        btnIsiSaldo.setForeground(Color.BLACK);
        btnLaporan.setForeground(Color.BLACK);
        btnPengguna.setForeground(Color.BLACK);
        btnTentang.setForeground(Color.BLACK);
        btnKeluar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int yesAndNoOption = JOptionPane.YES_NO_OPTION;
        
        btnDashboard.setForeground(Color.BLACK);
        btnDaftarSiswa.setForeground(Color.BLACK);
        btnTableTransfer.setForeground(Color.BLACK);
        btnIsiSaldo.setForeground(Color.BLACK);
        btnLaporan.setForeground(Color.BLACK);
        btnPengguna.setForeground(Color.BLACK);
        btnTentang.setForeground(Color.BLACK);
        btnKeluar.setForeground(Color.WHITE);
        
        int result = JOptionPane.showConfirmDialog(rootPane, "Anda yakin ingin keluar?", "Informasi", yesAndNoOption);
        
        if (result == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentangActionPerformed
        About about = new About();
        about.setVisible(true);
        showMenuBtn(btnTentang);

        btnDashboard.setForeground(Color.BLACK);
        btnDaftarSiswa.setForeground(Color.BLACK);
        btnTableTransfer.setForeground(Color.BLACK);
        btnIsiSaldo.setForeground(Color.BLACK);
        btnLaporan.setForeground(Color.BLACK);
        btnPengguna.setForeground(Color.BLACK);
        btnTentang.setForeground(Color.WHITE);
        btnKeluar.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_btnTentangActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        showContent(pnlLaporan);
        btnDashboard.setForeground(Color.BLACK);
        btnDaftarSiswa.setForeground(Color.BLACK);
        btnTableTransfer.setForeground(Color.BLACK);
        btnIsiSaldo.setForeground(Color.BLACK);
        btnLaporan.setForeground(Color.WHITE);
        btnPengguna.setForeground(Color.BLACK);
        btnTentang.setForeground(Color.BLACK);
        btnKeluar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnSimpanProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanProfileActionPerformed
        // TODO add your handling code here:
        warning();
    }//GEN-LAST:event_btnSimpanProfileActionPerformed

    private void tfProfileUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProfileUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProfileUsernameActionPerformed

    private void tfProfilePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProfilePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProfilePasswordActionPerformed

    private void btnPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenggunaActionPerformed
        // TODO add your handling code here:
        showContent(pnlPengguna);
        btnDashboard.setForeground(Color.BLACK);
        btnDaftarSiswa.setForeground(Color.BLACK);
        btnTableTransfer.setForeground(Color.BLACK);
        btnIsiSaldo.setForeground(Color.BLACK);
        btnLaporan.setForeground(Color.BLACK);
        btnPengguna.setForeground(Color.WHITE);
        btnTentang.setForeground(Color.BLACK);
        btnKeluar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnPenggunaActionPerformed

    private void btnShowProfilePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowProfilePasswordMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnShowProfilePasswordMouseClicked

    private void btnShowProfilePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowProfilePasswordActionPerformed
        warning();
    }//GEN-LAST:event_btnShowProfilePasswordActionPerformed

    private void cardKantin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardKantin1ActionPerformed
        // TODO add your handling code here:
        warning();
    }//GEN-LAST:event_cardKantin1ActionPerformed

    private void btnIsiSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsiSaldoActionPerformed
        // TODO add your handling code here:
        showContent(pnlIsiSaldo);
        
        btnDashboard.setForeground(Color.BLACK);
        btnDaftarSiswa.setForeground(Color.BLACK);
        btnTableTransfer.setForeground(Color.BLACK);
        btnIsiSaldo.setForeground(Color.WHITE);
        btnLaporan.setForeground(Color.BLACK);
        btnPengguna.setForeground(Color.BLACK);
        btnTentang.setForeground(Color.BLACK);
        btnKeluar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnIsiSaldoActionPerformed

    private void btnTableTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableTransferActionPerformed
        // TODO add your handling code here:
        showContent(pnlTableTransfer);
        
        btnDashboard.setForeground(Color.BLACK);
        btnDaftarSiswa.setForeground(Color.BLACK);
        btnTableTransfer.setForeground(Color.WHITE);
        btnIsiSaldo.setForeground(Color.BLACK);
        btnLaporan.setForeground(Color.BLACK);
        btnPengguna.setForeground(Color.BLACK);
        btnTentang.setForeground(Color.BLACK);
        btnKeluar.setForeground(Color.BLACK);
        
//        getTblTransfer().setFont(new Font("sansserif", Font.BOLD ,80));
        
//        List<TableTransfer> tableTransfer = new ArrayList<>();
//        tableTransfer.add(new TableTransfer(1, "bnu", "001", "50000", "/wkwkwkwk"));
//        tableTransfer.add(new TableTransfer(2, "anu", "100", "60000", "/qkwkwkwk"));
//        tblTransfer.setAutoCreateRowSorter(true); 
//        
//        TableTransferModel model = new TableTransferModel(tableTransfer);
//        model.fireTableDataChanged();
//
//        tblTransfer.setModel(model);
//        setMyActive(btnTableTransfer);
    }//GEN-LAST:event_btnTableTransferActionPerformed

    private void btnDaftarSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarSiswaActionPerformed
        // TODO add your handling code here:
        showContent(pnlDaftarSiswa);
        
        btnDashboard.setForeground(Color.BLACK);
        btnDaftarSiswa.setForeground(Color.WHITE);
        btnTableTransfer.setForeground(Color.BLACK);
        btnIsiSaldo.setForeground(Color.BLACK);
        btnLaporan.setForeground(Color.BLACK);
        btnPengguna.setForeground(Color.BLACK);
        btnTentang.setForeground(Color.BLACK);
        btnKeluar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnDaftarSiswaActionPerformed

    private void cardKantin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardKantin2ActionPerformed
        // TODO add your handling code here:
        warning();
    }//GEN-LAST:event_cardKantin2ActionPerformed

    private void cardKantin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardKantin3ActionPerformed
        // TODO add your handling code here:
        warning();
    }//GEN-LAST:event_cardKantin3ActionPerformed

    private void tblTransferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransferMouseEntered
        // TODO add your handling code here:
        
//        if (tblTransfer.getSelectedRow() != 0){
//            btnKonfirm.setEnabled(true);
//        } else {
//            btnKonfirm.setEnabled(false);
//        }
        
        
        
        
    }//GEN-LAST:event_tblTransferMouseEntered

    private void tblTransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransferMouseClicked
        // TODO add your handling code here:
        TableTransferModel model = (TableTransferModel) tblTransfer.getModel();
        int idTransfer = (int) model.getValueAt(tblTransfer.getSelectedRow(), 0);
        System.out.println("ini id : " + idTransfer);
        
//        add new confirm dialog
        KonfirmasiDialog konfirm = new KonfirmasiDialog();
//        JDialog dialog = new JDialog(konfirm);
        konfirm.getTfNamaWaliMuridDialog().setEditable(false);
        konfirm.getTfIdCardSiswaDialog().setEditable(false);
        konfirm.getTfNominalDialog().setEditable(false);
        konfirm.getTfStatusDialog().setEditable(false);
        
//        set text field value on confirm dialog
        konfirm.getTfNamaWaliMuridDialog().setText(
                model.getValueAt(tblTransfer.getSelectedRow(), 1).toString()
        );
        konfirm.getTfIdCardSiswaDialog().setText(
                model.getValueAt(tblTransfer.getSelectedRow(), 2).toString()
        );
        konfirm.getTfNominalDialog().setText(
                model.getValueAt(tblTransfer.getSelectedRow(), 3).toString()
        );
        konfirm.getTfStatusDialog().setText(
                model.getValueAt(tblTransfer.getSelectedRow(), 5).toString()
        );

//        add new btn listener and action
        konfirm.getBtnBatalDialog().addActionListener(Action -> {
            konfirm.dispose();
        });
        konfirm.getBtnKonfirmasiDialog().addActionListener(action -> {
            warning();
//            mainPanel.setEnabled(true);
        });
        
        konfirm.setResizable(false);
        konfirm.setExtendedState(JFrame.MAXIMIZED_HORIZ);
//        konfirm.setDefaultCloseOperation(J);
        konfirm.pack();
        konfirm.setLocationRelativeTo(null);
//        konfirm.setFocusable(true);
//        konfirm.requestFocus();
//        pnlContent.setEnabled(false);
//        konfirm.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        konfirm.setAlwaysOnTop(true);
        tblTransfer.setEnabled(false);
        scrlTableTransfer.setEnabled(false);
        
        konfirm.setVisible(true);
//        dialog.setVisible(true);
        
    }//GEN-LAST:event_tblTransferMouseClicked

    private void tblDaftarSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDaftarSiswaMouseClicked
        // TODO add your handling code here:
        DaftarSiswaModel model = (DaftarSiswaModel) tblDaftarSiswa.getModel();
        System.out.println("ini id siswa : " +  model.getValueAt(tblDaftarSiswa.getSelectedRow(),
                0));

        JOptionPane.showMessageDialog(mainPanel, 
                "Id \t: " + model.getValueAt(tblDaftarSiswa.getSelectedRow(), 0) + "\n" +
                "Nama \t: " + model.getValueAt(tblDaftarSiswa.getSelectedRow(), 1) + "\n" +
                "Id card \t: " + model.getValueAt(tblDaftarSiswa.getSelectedRow(), 3) + "\n" +
                "Saldo \t: " + model.getValueAt(tblDaftarSiswa.getSelectedRow(), 4),
                "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_tblDaftarSiswaMouseClicked

    private void tblTransfer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransfer1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTransfer1MouseClicked

    private void tblTransfer1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransfer1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTransfer1MouseEntered

    private void btnKonfirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKonfirm1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
                
                Dashboard dashboard = new Dashboard();
                dashboard.setSize((int) screen.getWidth(), (int) screen.getHeight());
                
//                dashboard.mainPanel.setSize((int) screen.getWidth() , (int) screen.getHeight());
                
//                menu panel
                dashboard.menuPanel.setSize(350, (int) screen.getHeight());
                
//                dashboard.cardKantin1.setText("<html> Kantin 1 <br> Rp " + dashboard.kantin.getKantin1() + "</html>");
//                dashboard.cardKantin2.setText("<html> Kantin 2 <br> Rp " + dashboard.kantin.getKantin2() + "</html>");
//                dashboard.cardKantin3.setText("<html> Kantin 3 <br> Rp " + dashboard.kantin.getKantin3() + "</html>");
//        
//        
//                System.out.println("\n\nBefor get kantin");
//                System.out.println(dashboard.kantin.getKantin1());
//                System.out.println(dashboard.kantin.getKantin2());
//                System.out.println(dashboard.kantin.getKantin3());
//                System.out.println("After get kantin");
                
//                dashboard.tblTransfer.setFont(new Font("sansserif", Font.BOLD ,80));
//                dashboard.tblTransfer.addMouseListener(mouseEvent -> {});
//                if (dashboard.tblTransfer.getSelectedRow() == 0){
//                    dashboard.btnKonfirm.setEnabled(false);
//                } else {
//                    dashboard.btnKonfirm.setEnabled(true);
//                }
                   
//                dashboard.btnKonfirm.setEnabled(false);
                dashboard.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftarSiswa;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnIsiSaldo;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKonfirm1;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnPengguna;
    private javax.swing.JButton btnShowProfilePassword;
    private javax.swing.JButton btnSimpanProfile;
    private javax.swing.JButton btnTableTransfer;
    private javax.swing.JButton btnTentang;
    private javax.swing.JButton cardKantin1;
    private javax.swing.JButton cardKantin2;
    private javax.swing.JButton cardKantin3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlDaftarSiswa;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlIsiSaldo;
    private javax.swing.JPanel pnlLaporan;
    private javax.swing.JPanel pnlPengguna;
    private javax.swing.JPanel pnlTableTransfer;
    private javax.swing.JPanel pnlTableTransferBackup;
    private javax.swing.JScrollPane scrlTableTransfer;
    private javax.swing.JScrollPane scrlTableTransfer1;
    private javax.swing.JTable tblDaftarSiswa;
    private javax.swing.JTable tblTransfer;
    private javax.swing.JTable tblTransfer1;
    private javax.swing.JPasswordField tfProfilePassword;
    private javax.swing.JTextField tfProfileUsername;
    // End of variables declaration//GEN-END:variables
    
    
    private TableTransfer selectedTblTransfer;
    private int selectedIndex;
    
//    getter
    public JPanel getPnlContent(){
        return this.pnlContent;
    }
    public JPanel getPnlDashboard(){
        return this.pnlDashboard;
    }
    public JPanel getPnlPengguna(){
        return this.pnlPengguna;
    }
    public JPanel getMainPanel(){
        return this.mainPanel;
    }

    
    
//    setter
    public void setTfProfileUsername(String user){
        tfProfileUsername.setText(user);
    }
    public void setTfProfilePassword(String user){
        tfProfilePassword.setText(user);
    }
    
    private void showContent(JPanel panel){
//        remove all panel
        pnlContent.removeAll();
        pnlContent.repaint();
        pnlContent.revalidate();
        
//        add new panel
        pnlContent.add(panel);
        pnlContent.repaint();
        pnlContent.revalidate();
    }
    private void showMenuBtn(JPanel panel, JButton button){
//        remove all panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
//        add new panel
        mainPanel.add(menuPanel);
        mainPanel.add(pnlContent);
        button.setForeground(Color.WHITE);
        showContent(panel);
        
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    private void showMenuBtn(JButton button){
//        remove all panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
//        add new panel
        mainPanel.add(menuPanel);
        mainPanel.add(pnlContent);
        button.setForeground(Color.WHITE);
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    // unsopprted :(
    private void setMyActive(JButton active){
        String[] item = {
            "Dashboard", "Daftar Siswa", "Table Transfer", "Isi Saldo",
            "Laporan", "Pengguna", "Tentang", "Keluar"
        };
        
        for (int i = 0; i < item.length; i++){
            if (item[i].equalsIgnoreCase(active.getText().toString()))
                active.setForeground(Color.WHITE);
            else
                active.setForeground(Color.BLACK);
        }
        System.out.println(active.getText());
        System.out.println(active.getText() == item[2]);
    }
    
    public PendapatanKantin getPendapatan(){
        return this.kantin;
    } 
    
    public JButton getKantin1(){
        return this.cardKantin1;
    }
    public JButton getKantin2(){
        return this.cardKantin2;
    }
    public JButton getKantin3(){
        return this.cardKantin3;
    }
    public JButton getBtnDashboard(){
        return this.btnDashboard;
    }
    
    public void warning(){
        int warning = JOptionPane.YES_OPTION;
        JOptionPane.showMessageDialog(mainPanel, "Maaf aplikasi ini masih dalam pengembangan,"
                + " \nbeberapa fungsi mungkin tidak bekerja seperti seharusnya!", "Informasi", 
                JOptionPane.INFORMATION_MESSAGE);
    }
    public JTable getTblTransfer(){
        return this.tblTransfer;
    }
    public JTable getTblDaftarSiswa(){
        return this.tblDaftarSiswa;
    }
    public JTable getTblDftrSiswa(){
        return this.tblDaftarSiswa;
    }
    
    
//    private static class PendapatanKantinTableModel extends AbstractTableModel{
//        private final String[] columnTable = {
//            "ID", "WALI MURID", "ID CARD SISWA", "TOTAL", "BUKTI"
//        };
//        private List<TableTransfer> table;
//
//        public PendapatanKantinTableModel(List<TableTransfer> table) {
//            this.table = table;
//        }
//        
//        @Override
//        public int getRowCount() {
//            return table.size();
//        }
//
//        @Override
//        public int getColumnCount() {
//            return columnTable.length;
//        }
//
//        @Override
//        public Object getValueAt(int i, int i1) { // mengisi setiap kolom pada table 
//            return switch (i1){
//                case 0 -> table.get(i).getId();
//                case 1 -> table.get(i).getNamaWali();
//                case 2 -> table.get(i).getIdCardSiswa();
//                case 3 -> table.get(i).getTotal();
//                case 4 -> table.get(i).getBukti();
//                default -> "-";
//            };
//        }
//        @Override
//        public String getColumnName(int index){
//            return columnTable[index];
//        }
//        @Override
//        public Class<?> getColumnClass(int index){ // merepresentasikan setiap object pada table agar lebih manusiawi  
//            if (getValueAt(0, index) != null)
//                return getValueAt(0, index).getClass();
//            else
//                return Object.class;
//        }
//    }
}